### ISSUE TITLE
source / build code?

### ISSUE THREAD

**Issue by kiwicopple** [niutech/amp-spectre#1]
Hey, this is amazing work that you've done. I tried it out on one of my sites and decided I'm going to convert a few more.

Do you have the raw code (unminified?) that you used to build this? I would like to modify some of the colours and the pre/code tags, and it would be helpful if I can just put them through my build process.

Other than that, I just want to say thanks.

**Comment by niutech** [comment]
Thank you! Sorry, I did it in an oldschool way by modifying the minified CSS file. There is no build step. But you can deminify it using any CSS beautifier.

**Comment by kiwicopple** [comment]
Aha, not a problem. Thanks anyway!

**Comment by niutech** [comment]
Here is the [SCSS file](https://github.com/niutech/amp-spectre/blob/master/spectre.scss)
