### ISSUE TITLE
Partials 

### ISSUE THREAD

**Issue by virgiltu** [niutech/amp-spectre#4]
Not really an issues. But since is mostly made for amp, would it not make sense to just brake it down into parts. Main, buttons, menus, etc/

**Comment by niutech** [comment]
Good suggestion, I will make it when I have more time, for now I suggest you to use [css2sass](https://css2sass.herokuapp.com/).

**Comment by niutech** [comment]
I have generated the [SCSS file](https://github.com/niutech/amp-spectre/blob/master/spectre.scss) so you can divide it into parts.
